FROM python:3.10-slim

WORKDIR /app

COPY requirements.txt .

RUN apt-get update && apt-get install -y --no-install-recommends build-essential gcc ffmpeg && \
    pip install --no-cache-dir -r requirements.txt

COPY streamlit ./streamlit
COPY example_portfolio.json .

EXPOSE 8501

CMD ["streamlit", "run", "streamlit/app.py", "--server.port=8501", "--server.address=0.0.0.0"]